### ISSUE TITLE
inspect fails

### ISSUE THREAD

**Issue by aunderwo** [assemblerflow/flowcraft#114] opened 2018-07-26 23:29 UTC
When I use the flowcraft inspect function on a non-flowcradt pipeline, initially it works but as soon as the 1st task completes an error occurs

```
$ flowcraft inspect -m overview
could not convert string to float: '-'(anaconda3-5.2.0) 

$ flowcraft inspect -m broadcast
Preparing broadcast data...
WARNING: dotfile named .treeDag.json not found or corrupted
Starting broadcast. You can see the pipeline progress on the link below:
http://192.92.149.169:80/inspect/1e7d959a0a5e7ef4b062332089fa5a8d889d26cdf53e248ad117244540cdd42a
ERROR: <class 'ValueError'>
Closing connection
```

I know this is not an officially supported function of the software so can understand if you do not wish to debug but thought I would record the issue.

Thanks

**Comment by ODiogoSilva** [comment] 2018-07-27 07:39
Hi,

We would like to offer support for general nextflow pipelines whenever possible.

Can you provide the nextflow log and trace files of a failing inspection for debugging?

**Comment by aunderwo** [comment] 2018-07-27 09:36
Thanks.

I am running the latest version of nextflow 0.31.0. 
I wonder if it's because it's trying to convert a xx.x% string to a float?

pipeline_stats.txt

```
task_id	hash	process	tag	status	exit	start	container	cpus	time	disk	memory	duration	realtime	queue	%cpu	%memrss	vmem	rchar	wchar
1	20/f4eec0	qc_pre_trimming	-	COMPLETED	0	2018-07-27 10:29:08.652	assembly	1	-	-	-	1m 22s	1m 17s	-	47.3%	14.0%	281.3 MB	2.8 GB	154.9 MB	2.3 MB
2	df/25bd5c	qc_pre_trimming	-	ABORTED	-	2018-07-27 10:29:08.645	assembly	1	-	-	-	-	-	-	--	-	-	-	-
3	fd/f202c7	trimming	-	ABORTED	-	2018-07-27 10:29:08.649	assembly	1	-	-	-	-	-	-	--	-	-	-	-
4	ed/64db08	trimming	-	ABORTED	-	2018-07-27 10:29:08.653	assembly	1	-	-	-	-	-	-	--	-	-	-	-
```

.nextflow.log
```
Jul-27 10:28:55.811 [main] DEBUG nextflow.cli.Launcher - $> /usr/local/bin/nextflow run Documents/provisioning/packer/assembly_virualbox+vagrant_digitalocean_docker/files_for_vm/assembly.nf --input_dir /Users/au3/sanger_google_drive/documents/training/Assembly/fastq_files --output_dir /Users/au3/sanger_google_drive/documents/training/Assembly/nextflow_output --fastq_pattern *_{1,2}.fastq.gz --adapter_file Documents/provisioning/packer/assembly_virualbox+vagrant_digitalocean_docker/files_for_vm/adapters.fas -with-docker assembly -resume
Jul-27 10:28:55.972 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.31.0
Jul-27 10:28:56.004 [main] INFO  nextflow.cli.CmdRun - Launching `Documents/provisioning/packer/assembly_virualbox+vagrant_digitalocean_docker/files_for_vm/assembly.nf` [friendly_galileo] - revision: 9ed2dab29a
Jul-27 10:28:56.070 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Users/au3/nextflow.config
Jul-27 10:28:56.071 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/au3/nextflow.config
Jul-27 10:28:56.148 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jul-27 10:28:56.707 [main] DEBUG nextflow.config.ConfigBuilder - Enabling execution in Docker container as requested by cli option `-with-docker assembly`
Jul-27 10:28:56.748 [main] DEBUG nextflow.Session - Session uuid: dd410867-f6b9-4c40-aa6c-c93363642d11
Jul-27 10:28:56.748 [main] DEBUG nextflow.Session - Run name: friendly_galileo
Jul-27 10:28:56.749 [main] DEBUG nextflow.Session - Executor pool size: 4
Jul-27 10:29:06.795 [main] DEBUG nextflow.cli.CmdRun -
  Version: 0.31.0 build 4885
  Modified: 25-07-2018 14:10 UTC (15:10 BST)
  System: Mac OS X 10.12.6
  Runtime: Groovy 2.4.15 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_181-b13
  Encoding: UTF-8 (UTF-8)
  Process: 16159@loan109148.local [172.20.240.136]
  CPUs: 4 - Mem: 8 GB (107.3 MB) - Swap: 4 GB (778.2 MB)
Jul-27 10:29:06.818 [main] DEBUG nextflow.Session - Work-dir: /Users/au3/work [Mac OS X]
Jul-27 10:29:06.819 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/au3/Documents/provisioning/packer/assembly_virualbox+vagrant_digitalocean_docker/files_for_vm/bin
Jul-27 10:29:07.187 [main] DEBUG nextflow.Session - Session start invoked
Jul-27 10:29:07.191 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Jul-27 10:29:07.193 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /Users/au3/pipeline_stats.txt
Jul-27 10:29:07.198 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Jul-27 10:29:07.587 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-27 10:29:07.595 [main] INFO  nextflow.Nextflow - ======================================================================
Jul-27 10:29:07.596 [main] INFO  nextflow.Nextflow -                   GHRU assembly pipeline
Jul-27 10:29:07.596 [main] INFO  nextflow.Nextflow - ======================================================================
Jul-27 10:29:07.596 [main] INFO  nextflow.Nextflow - Running version   : 1.0
Jul-27 10:29:07.597 [main] INFO  nextflow.Nextflow - Fastqs            : /Users/au3/sanger_google_drive/documents/training/Assembly/fastq_files/*_{1,2}.fastq.gz
Jul-27 10:29:07.597 [main] INFO  nextflow.Nextflow - Adapter file      : Documents/provisioning/packer/assembly_virualbox+vagrant_digitalocean_docker/files_for_vm/adapters.fas
Jul-27 10:29:07.597 [main] INFO  nextflow.Nextflow - ======================================================================
Jul-27 10:29:07.597 [main] INFO  nextflow.Nextflow - Outputs written to path '/Users/au3/sanger_google_drive/documents/training/Assembly/nextflow_output'
Jul-27 10:29:07.597 [main] INFO  nextflow.Nextflow - ======================================================================
Jul-27 10:29:07.597 [main] INFO  nextflow.Nextflow -
Jul-27 10:29:07.651 [main] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /Users/au3/sanger_google_drive/documents/training/Assembly/fastq_files/; pattern: *_{1,2}.fastq.gz; options: [:]
Jul-27 10:29:08.055 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.055 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.064 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.067 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Jul-27 10:29:08.078 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=4; memory=8 GB; capacity=4; pollInterval=100ms; dumpInterval=5m
Jul-27 10:29:08.090 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Jul-27 10:29:08.103 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Jul-27 10:29:08.139 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Jul-27 10:29:08.200 [main] DEBUG nextflow.Session - >>> barrier register (process: qc_pre_trimming)
Jul-27 10:29:08.204 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > qc_pre_trimming -- maxForks: 4
Jul-27 10:29:08.265 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.266 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.266 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.268 [main] DEBUG nextflow.Session - >>> barrier register (process: trimming)
Jul-27 10:29:08.268 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > trimming -- maxForks: 4
Jul-27 10:29:08.299 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.300 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.301 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.304 [main] DEBUG nextflow.Session - >>> barrier register (process: qc_post_trimming)
Jul-27 10:29:08.305 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > qc_post_trimming -- maxForks: 4
Jul-27 10:29:08.320 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.320 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.320 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.322 [main] DEBUG nextflow.Session - >>> barrier register (process: genome_size_estimation)
Jul-27 10:29:08.326 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > genome_size_estimation -- maxForks: 4
Jul-27 10:29:08.382 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.383 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.383 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.384 [main] DEBUG nextflow.Session - >>> barrier register (process: read_correction)
Jul-27 10:29:08.384 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > read_correction -- maxForks: 4
Jul-27 10:29:08.392 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.392 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.392 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.394 [main] DEBUG nextflow.Session - >>> barrier register (process: count_number_of_reads)
Jul-27 10:29:08.395 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > count_number_of_reads -- maxForks: 4
Jul-27 10:29:08.413 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.413 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.413 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.414 [main] DEBUG nextflow.Session - >>> barrier register (process: merge_reads)
Jul-27 10:29:08.415 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > merge_reads -- maxForks: 4
Jul-27 10:29:08.423 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.423 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.424 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.427 [main] DEBUG nextflow.Session - >>> barrier register (process: spades_assembly)
Jul-27 10:29:08.430 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > spades_assembly -- maxForks: 4
Jul-27 10:29:08.442 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-27 10:29:08.442 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-27 10:29:08.442 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-27 10:29:08.443 [main] DEBUG nextflow.Session - >>> barrier register (process: quast)
Jul-27 10:29:08.444 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > quast -- maxForks: 4
Jul-27 10:29:08.446 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Jul-27 10:29:08.446 [main] DEBUG nextflow.Session - Session await
Jul-27 10:29:08.478 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jul-27 10:29:08.487 [Task submitter] INFO  nextflow.Session - [df/25bd5c] Submitted process > qc_pre_trimming (2)
Jul-27 10:29:08.523 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jul-27 10:29:08.524 [Task submitter] INFO  nextflow.Session - [fd/f202c7] Submitted process > trimming (1)
Jul-27 10:29:08.548 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jul-27 10:29:08.549 [Task submitter] INFO  nextflow.Session - [20/f4eec0] Submitted process > qc_pre_trimming (1)
Jul-27 10:29:08.558 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jul-27 10:29:08.559 [Task submitter] INFO  nextflow.Session - [ed/64db08] Submitted process > trimming (2)
Jul-27 10:30:31.012 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: qc_pre_trimming (1); status: COMPLETED; exit: 0; error: -; workDir: /Users/au3/work/20/f4eec0f4abcd102fcff8415c386215]
Jul-27 10:30:40.140 [SIGINT handler] DEBUG nextflow.Session - Session aborted -- Cause: SIGINT
Jul-27 10:30:40.242 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Jul-27 10:30:40.250 [SIGINT handler] DEBUG nextflow.Session - The following nodes are still active:
[process] qc_post_trimming
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] genome_size_estimation
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] read_correction
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] count_number_of_reads
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] merge_reads
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] spades_assembly
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] quast
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

Jul-27 10:30:40.257 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-27 10:30:40.257 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-27 10:30:40.304 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (3)
Jul-27 10:30:40.328 [Actor Thread 1] DEBUG nextflow.Session - <<< barrier arrive (process: read_correction)
Jul-27 10:30:40.388 [Actor Thread 1] DEBUG nextflow.Session - <<< barrier arrive (process: merge_reads)
Jul-27 10:30:40.478 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=1; failedCount=3; ignoredCount=0; cachedCount=0; succeedDuration=1m 17s; failedDuration=0ms; cachedDuration=0ms]
Jul-27 10:30:40.478 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file
Jul-27 10:30:40.500 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jul-27 10:30:40.538 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

**Comment by ODiogoSilva** [comment] 2018-07-30 08:33
So, the problem in this case is that the `memory` field in the trace file was not set for the first process (has a `-` value). Flowcraft pipelines always set a value for this field, so we're not expecting this behaviour. This is now fixed on the `dev` branch and will release a new version with the fix soon.

**Comment by aunderwo** [comment] 2018-08-02 09:11
Fantastic I will try this out from dev

**Comment by aunderwo** [comment] 2018-08-02 09:56
Hmm it now errors as follows

```
flowcraft inspect -i trace.txt
'process'

more trace.txt
task_id hash    native_id       name    status  exit    submit  duration        realtime        %cpu    rss     vmem    rchar   wchar
2       e3/1d76e0       95454   qc_pre_trimming (1)     COMPLETED       0       2018-08-02 10:49:37.719 1m 29s  1m 22s  51.3%   272.2 MB        2.8 GB  168.3 MB        3.5 MB
1       cc/06da24       95452   qc_pre_trimming (2)     COMPLETED       0       2018-08-02 10:49:37.792 2m 18s  2m 12s  66.2%   271 MB  2.8 GB  514.7 MB        2.6 MB
3       a9/92582d       95453   trimming (1)    COMPLETED       0       2018-08-02 10:49:37.779 4m 12s  4m 10s  84.4%   184.3 MB        3 GB    128.2 MB        122.7 MB
7       b3/b57d1d       95860   count_number_of_reads (1)       COMPLETED       0       2018-08-02 10:53:49.773 13.8s   6.8s    40.9%   5.3 MB  28.3 MB 61.5 MB 0
6       14/fc77fa       95858   genome_size_estimation (1)      COMPLETED       0       2018-08-02 10:53:49.749 49.5s   45.6s   62.3%   23.4 MB 123.6 MB        56.5 MB 34 B
```

**Comment by ODiogoSilva** [comment] 2018-08-02 10:02
This trace file seems to be missing a mandatory field for the inspect to work, the `tag` field. 

You can check the two mandatory trace fields (and other optional ones) here:
https://flowcraft.readthedocs.io/en/latest/user/pipeline_inspect.html#trace-fields

Flowcraft currently uses the  `tag` as a sample/job identifier

**Comment by aunderwo** [comment] 2018-08-02 13:54
Thank you that's done the trick. Up and running!!
![image](https://user-images.githubusercontent.com/423/43588237-f5d88ebe-9663-11e8-8a76-d030762e2ea7.png)

**Comment by ODiogoSilva** [comment] 2018-08-02 13:56
:+1: Enjoy and let us know of any other issue. I'll close the issue in the next release.

**Comment by jacarrico** [comment] 2018-08-02 15:19
Keep those bugs/suggestions flowing ;-) 
I see great potential in plugging in flowcraft/nextflow pipelines to wgsa and microreact ;)

**Comment by aunderwo** [comment] 2018-08-02 15:48
@jacarrico 
Thanks João  - yes my current idea is to use nextflow and hopefully flowcraft as a means to allow partners to run and **monitor**  bioinf analyses that can feed into downstream tools (e.g microreact). The question is how to make the bar as low as possible so that you don't have to be a CLI wizard to get this up and running easily.

**Comment by jacarrico** [comment] 2018-08-02 16:02
Then we have to do a demo of the INNUENDO platform for your to give you a good example on that ;-) We can try to arrange this next week if you are available.  Drop me an email.

**Comment by aunderwo** [comment] 2018-08-29 10:03
Hi all.
I am now trying flowcraft again on a vanilla ubuntu box and am getting a failure

```Preparing broadcast data...
WARNING: dotfile named .treeDag.json not found or corrupted
Starting broadcast. You can see the pipeline progress on the link below:
http://192.92.149.169:80/inspect/XXXXXXXXXXXXXXXXXXXXXXXXXX
ERROR: <class 'ValueError'>
Closing connection
```
I attach the pipeline_stats.txt
[pipeline_stats.txt](https://github.com/assemblerflow/flowcraft/files/2331699/pipeline_stats.txt)

**Comment by ODiogoSilva** [comment] 2018-08-29 10:10
Hi @aunderwo 

Can you also provide the .nextflow.log file to reproduce the issue?

**Comment by aunderwo** [comment] 2018-08-29 10:12
Sorry ignore that - I had the nextflow.config in the wrong place - doh!!!

**Comment by aunderwo** [comment] 2018-08-29 10:17
Ahh doh again. It works fine for the first few minutes then fails

log file attached
[nextflow.log](https://github.com/assemblerflow/flowcraft/files/2331731/nextflow.log)

**Comment by ODiogoSilva** [comment] 2018-08-29 10:26
Ah, I see you are using flowcraft from pip/conda, which does not have the latest bug fixes for the inspect mode. Running inspect with the 1.2.1 pip/conda version fails, but running with the `dev` code it should run well.

I've been delaying the next release to incorporate the new reports mode that we've been working on but I'll make an intermediate release to include these bug fixes in the stable version.

**Comment by aunderwo** [comment] 2018-08-29 12:06
That makes sense. This was a new install and I checked out from GitHub but
I forgot to check out develop. Apologies

**Closed** 2018-08-29 13:26 UTC

**Comment by cimendes** [comment] 2018-08-29 15:01
Closed this issue as it has been fixed in the newest release https://github.com/assemblerflow/flowcraft/releases/tag/1.2.2

**Comment by aunderwo** [comment] 2018-08-29 16:48
Thanks @cimendes  and @ODiogoSilva - the new release has fixed the issue :) 
Saves me having to remember to checkout develop! 😊

**Comment by cimendes** [comment] 2018-08-30 09:28
You're welcome! :)
